### ISSUE TITLE
[REQUEST] Framework for Perk-Requirements

### ISSUE THREAD

**Issue by Darxo** [MSUTeam/MSU#140]
**Is your feature request related to a problem? Please describe.**
Certain new perks introduced by mods like **Legends** or **PTR** build upon other perks to a point where one perk will **not** work if you have not picked a certain other perk first.

**Examples:**
1. The legends perk **Spiritual Bond** only works while your Vala has an active **Warden** summoned. But the only way to summon a **Warden** is having the perk **Warden** specced in the first place. So **Spiritual Bond** is completely useless otherwise and should be unable to be learned by accident
2. The PTR perk **Weapon Master** only works if you have also picked up one of the applicable **Weapon Masteries**.
3. The legends perk **Inscription Mastery** improves the speed at which you can make runes. But the only way to make runes is having one of the other rune-perks picked up first.
4. The legends perk **Chant Mastery** improves usage of chants but in order to have access to those, you have to pick other perks first.

**Describe the solution you'd like**
Introduce a system where modder can optionally define perk-requirements when they create new perks.
If those requirements are met (on top of the vanilla requirement of being the correct level) then you can learn this perk. All other methods that forcibly learn a perk for you ignore this requirement. For example **Professional** or Origin-Specific boni

Those requirements could be:
- Requires one or more perks out of a given list
- Requires all perks given in a list
- Requires at least X perks from a certain Perk-Group (most likely the same perk-group that this is from)

**Comment by Enduriel** [comment]
I think this is outside the scope of MSU. These are systems added by mods and MSU is meant to make vanilla more moddable, not make other mods more moddable

**Comment by LordMidas** [comment]
I personally don't think this is outside the scope. As allowing some perks to be dependent on other perks could be argued to be a "improving vanilla moddability" feature too because one could say it allows e.g. making Killing Frenzy require Berserk etc. However, I think it will require us to do a rather major overhaul of how Perks are handled in the game (aka PerkDefObjects and PerkDefs system as Legends uses). Because I see no other way of storing in a perk the information about what other perks it requires.

**Comment by Darxo** [comment]
Storing the information sounded to me like the easy part.
I thought about something simple like an array of perkIDs inside the respective perk_MYCUSTOMPERK.nut files which currently already contain most information about the perks.

So far this is on the modders end. MSU just tells you that if you want to use this feature you gotta have a variable in your perk called **PerkRequirements** (for example)

The complicated parked seemed to be the hooks into the vanilla behaviour where they grey-out or unlock perks. Currently this only happens dependent on the amount of your brothers currently spent perks.
And then the updated tooltip about why you can't specc into this perk yet.
So here MSU does the work by checking whether the **PerkRequirements** variable exists in the respective perk and then checks whether you fullfil these requirements.

**Comment by Enduriel** [comment]
Oh I see, I misunderstood the question at first, I agree this is within scope. This seems doable then tbh, the grey-out/unlock part is easy. I agree with @LordMidas that the structural part here would be more complex because I'm not sure if storing this in the perk nut would be optimal vs the perkdefs array... hard to say without digging into this more.

**Comment by Darxo** [comment]
Additionally this system could be extended to also allow you to define perks that **prevent** you from picking other perks.

A good example from the past is how **Clarity** was conflicting with **Berserk** for balance reasons. One wouldn't work if you had specced the other.
So instead they could have defined that the respective other perk couldn't even be specced in the first place.

**Comment by LordMidas** [comment]
Closing, as this is being implemented separately in another framework that we are working on.
